### ISSUE TITLE
Support for spring batch 5.1.x

### ISSUE THREAD

**Issue by acktsap** [naver/spring-batch-plus#42]
### [v5.1.0-M1](https://github.com/spring-projects/spring-batch/releases/tag/v5.1.0-M1)

- [x] [Add support for Virtual Threads](https://github.com/spring-projects/spring-batch/issues/4399) : Just check
- [x] [Add setter for ObservationConvention in StepBuilder/JobBuilder](https://github.com/spring-projects/spring-batch/issues/4401) : Add method

### [v5.1.0-M2](https://github.com/spring-projects/spring-batch/releases/tag/v5.1.0-M2)

- [x] [Deprecate jobRepository method in JobBuilderHelper & StepBuilderHelper](https://github.com/spring-projects/spring-batch/issues/4326) : Deprecate the method

### [v5.1.0-M3](https://github.com/spring-projects/spring-batch/releases/tag/v5.1.0-M3)

- [x] [Add ability to start a job flow definition with a decider](https://github.com/spring-projects/spring-batch/issues/4411) : Check if need refactoring

### [v5.1.0-RC1](https://github.com/spring-projects/spring-batch/releases/tag/v5.1.0-RC1)

Nothing to check
 
### [v5.1.0](https://github.com/spring-projects/spring-batch/releases/tag/v5.1.0)

- [x] [Deprecate method](https://github.com/spring-projects/spring-batch/commit/89e0a0cd86d9072473338813d7d63d5c5a5f26b3) : Not needed

### Update sample

- [x] Done

### Update Docs

- [x] Done
